version: '3'

services:
  vmaas_database:
    container_name: vmaas-database
    build:
        context: .
        dockerfile: ./database/Dockerfile
    image: vmaas/database:latest
    restart: unless-stopped
    env_file:
      - ./conf/database-connection-admin.env
    ports:
      - 5432:5432
    volumes:
      - vmaas-db-data:/var/lib/pgsql/data

volumes:
  vmaas-db-data: